version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
  db:
    image: postgress:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=this_is_django
      - POSTGRES_PASSWORD=wr_django
      - POSTGRES_DB=this_is_django_db
volumes: postgres_data
